package com.codingcat.aipersonalfinance.domain.ledger.dto;

import com.codingcat.aipersonalfinance.domain.ledger.Category;
import com.codingcat.aipersonalfinance.domain.ledger.Ledger;
import com.codingcat.aipersonalfinance.domain.ledger.LedgerType;
import com.codingcat.aipersonalfinance.domain.ledger.PaymentMethod;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;

/**
 * 거래 내역 응답 DTO
 */
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class LedgerResponse {

  private Long ledgerIdx;
  private LedgerType type;
  private BigDecimal amount;
  private String desc;
  private String place;
  private Category category;
  private PaymentMethod paymentMethod;
  private LocalDate recordedDate;
  private Boolean isAutoGenerated;
  private LocalDateTime createdAt;
  private LocalDateTime modifiedAt;

  /**
   * Ledger 엔티티를 LedgerResponse DTO로 변환합니다.
   */
  public static LedgerResponse from(Ledger ledger) {
    return LedgerResponse.builder()
        .ledgerIdx(ledger.getIdx())
        .type(ledger.getType())
        .amount(ledger.getAmount())
        .desc(ledger.getDesc())
        .place(ledger.getPlace())
        .category(ledger.getCategory())
        .paymentMethod(ledger.getPaymentMethod())
        .recordedDate(ledger.getRecordedDate())
        .isAutoGenerated(ledger.getIsAutoGenerated())
        .createdAt(ledger.getCreatedAt())
        .modifiedAt(ledger.getModifiedAt())
        .build();
  }
}
