package com.codingcat.aipersonalfinance.domain.ledger;

import com.codingcat.aipersonalfinance.domain.BaseEntity;
import com.codingcat.aipersonalfinance.domain.recurring.RecurringTransaction;
import com.codingcat.aipersonalfinance.domain.user.User;
import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.PastOrPresent;
import jakarta.validation.constraints.PositiveOrZero;
import java.math.BigDecimal;
import java.time.LocalDate;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.SQLRestriction;

/**
 * 가계부 거래 내역 엔티티
 * 사용자의 수입/지출 거래 정보를 관리합니다.
 */
@Entity
@Table(name = "ledger")
@Getter
@NoArgsConstructor
@AllArgsConstructor
@Builder
@SQLRestriction("deleted_at IS NULL")
public class Ledger extends BaseEntity {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "ledger_idx")
  private Long idx;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "user_idx", nullable = false)
  @Schema(description = "가계부 소유자")
  private User user;

  @Schema(description = "INCOME: 수입, EXPENSE: 지출")
  @Enumerated(EnumType.STRING)
  @Column(nullable = false, length = 20)
  private LedgerType type;

  @PositiveOrZero
  @Column(nullable = false, precision = 15, scale = 2)
  private BigDecimal amount;

  @Schema(description = "사용 내역")
  @Column(nullable = false, length = 255)
  private String desc;

  @Schema(description = "사용처")
  @Column(length = 100)
  private String place;

  @Enumerated(EnumType.STRING)
  @Column(nullable = false, length = 50)
  private Category category;

  @Enumerated(EnumType.STRING)
  @Column(name = "payment_method", nullable = false, length = 50)
  private PaymentMethod paymentMethod;

  @PastOrPresent
  @Column(name = "recorded_date", nullable = false)
  private LocalDate recordedDate;

  @Schema(description = "정기 거래로부터 자동 생성되었는지 여부")
  @Column(name = "is_auto_generated", nullable = false)
  @Builder.Default
  private Boolean isAutoGenerated = false;

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "recurring_transaction_idx")
  @Schema(description = "원본 정기 거래 (자동 생성된 경우)")
  private RecurringTransaction recurringTransaction;
}